//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.269
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thrak.Resources.Localization.Classes {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Math {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Math() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thrak.Resources.Localization.Classes.Math", typeof(Math).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Division by zero..
        /// </summary>
        internal static string XMathDividByZero {
            get {
                return ResourceManager.GetString("XMathDividByZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Definition error in the function table of the Expression object :the function &apos;{0}&apos; is not defined for class &apos;{1}&apos;..
        /// </summary>
        internal static string XMathExprCorruptedFunctionTable {
            get {
                return ResourceManager.GetString("XMathExprCorruptedFunctionTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The supplied expression is empty..
        /// </summary>
        internal static string XMathExprEmpty {
            get {
                return ResourceManager.GetString("XMathExprEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid argument count for function {0}() ; expected = {1},supplied = {2}..
        /// </summary>
        internal static string XMathExprIncorrectArgc {
            get {
                return ResourceManager.GetString("XMathExprIncorrectArgc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid floating-point number : &apos;{0}&apos;..
        /// </summary>
        internal static string XMathExprInvalidFloat {
            get {
                return ResourceManager.GetString("XMathExprInvalidFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is no function {0}() accepting {1} argument(s)..
        /// </summary>
        internal static string XMathExprInvalidFunction {
            get {
                return ResourceManager.GetString("XMathExprInvalidFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid operator &apos;{0}&apos;..
        /// </summary>
        internal static string XMathExprInvalidOperator {
            get {
                return ResourceManager.GetString("XMathExprInvalidOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Evaluate() method has been called, but there is no expression to evaluate..
        /// </summary>
        internal static string XMathExprNothingToEval {
            get {
                return ResourceManager.GetString("XMathExprNothingToEval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Syntax error, unexpected token found : &apos;{0}&apos;..
        /// </summary>
        internal static string XMathExprUnexpectedToken {
            get {
                return ResourceManager.GetString("XMathExprUnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The base of a number must be between 2 and 36..
        /// </summary>
        internal static string XMathInvalidBase {
            get {
                return ResourceManager.GetString("XMathInvalidBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The digit &quot;{0}&quot; is not valid for number base {1}..
        /// </summary>
        internal static string XMathInvalidBaseNumber {
            get {
                return ResourceManager.GetString("XMathInvalidBaseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot compute the factorial of a negative number..
        /// </summary>
        internal static string XMathNegativeFactorial {
            get {
                return ResourceManager.GetString("XMathNegativeFactorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The lower value of a sum cannot be greater than its upper value..
        /// </summary>
        internal static string XMathSumError {
            get {
                return ResourceManager.GetString("XMathSumError", resourceCulture);
            }
        }
    }
}
