//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.269
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thrak.Resources.Localization.Classes {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Stack {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Stack() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thrak.Resources.Localization.Classes.Stack", typeof(Stack).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The requested operation cannot be performed on an empty stack..
        /// </summary>
        internal static string XStackEmpty {
            get {
                return ResourceManager.GetString("XStackEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified number of elements ({0}) must be greater than zero..
        /// </summary>
        internal static string XStackInvalidCount {
            get {
                return ResourceManager.GetString("XStackInvalidCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified number of elements ({0}) must be greater than or equal to two..
        /// </summary>
        internal static string XStackInvalidCount2 {
            get {
                return ResourceManager.GetString("XStackInvalidCount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified increment value ({0}) cannot be less than 1..
        /// </summary>
        internal static string XStackInvalidGrowth {
            get {
                return ResourceManager.GetString("XStackInvalidGrowth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified index ({0}) is invalid and must range from 0 to {1}..
        /// </summary>
        internal static string XStackInvalidIndex {
            get {
                return ResourceManager.GetString("XStackInvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stack overflow, maximum stack size = {0}..
        /// </summary>
        internal static string XStackOverflow {
            get {
                return ResourceManager.GetString("XStackOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Remove() operation on a Stack&lt;&gt; object is not supported..
        /// </summary>
        internal static string XStackRemoveUnsupported {
            get {
                return ResourceManager.GetString("XStackRemoveUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified number of values ({1}) is greater than stack size ({0})..
        /// </summary>
        internal static string XStackSmallerThanInitValues {
            get {
                return ResourceManager.GetString("XStackSmallerThanInitValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stack underflow..
        /// </summary>
        internal static string XStackUnderflow {
            get {
                return ResourceManager.GetString("XStackUnderflow", resourceCulture);
            }
        }
    }
}
