/**************************************************************************************************************

    NAME
        WinAPI/Structures/H/HARDWAREINPUT.cs

    DESCRIPTION
        HARDWAREINPUT structure.

    AUTHOR
        Christian Vigh, 09/2012.

    HISTORY
    [Version : 1.0]    [Date : 2012/09/14]     [Author : CV]
        Initial version.

 **************************************************************************************************************/

using	System  ;
using	System. Runtime. InteropServices  ;
using   System. Text ;

using	Thrak. WinAPI ;
using	Thrak. WinAPI. Enums ;


namespace Thrak. WinAPI. Structures
   {
	/// <summary>
	/// Contains information about a simulated message generated by an input device other than a keyboard or mouse. 
	/// </summary>
 	[StructLayout ( LayoutKind. Sequential ) ]
	public struct  HARDWAREINPUT
	   {
		/// <summary>
		/// The message generated by the input hardware. 
		/// </summary>
		public uint		uMsg ;

		/// <summary>
		/// The low-order word of the lParam parameter for uMsg. 
		/// </summary>
		public ushort		wParamL ;

		/// <summary>
		/// The high-order word of the lParam parameter for uMsg. 
		/// </summary>
		public ushort		wParamH ;


		/// <summary>
		/// Converts a WinAPI.Structure object into an initialized HARDWAREINPUT structure. This is only syntactical sugar to zero out a structure
		/// using the Structure.Empty property.
		/// </summary>
		/// <returns>An initialized HARDWAREINPUT structure.</returns>
		public static implicit operator  HARDWAREINPUT ( Thrak. WinAPI. Structures. Structure  value )
		   {
			HARDWAREINPUT		Result ;

			Result. uMsg		=  0 ;
			Result. wParamL		=  0 ;
			Result. wParamH		=  0 ;

			return ( Result ) ;
		    }
	    }
    }